apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: sample-app
spec:
    replicas: 2
    template:
        metadata:
            labels:
                app: sample-app
        spec:
            containers:
            - name: sample-app
              image: java-sample-demo:0.1
              image-pull-policy: Never
              ports:
              - containerPort: 8080
