apiVersion: v1
kind: Service
metadata:
    name: sample-app
spec:
    selector:
        app: sample-app
    ports:
        - name: sample-app
          protocol: TCP
          port: 8080
    type: LoadBalancer
